language: node_js
node_js:
  - "16"
addons:
  chrome: stable
  firefox: latest
notifications:
  slack:
    secure: JKzk2sJSbZ9h2PUVWj6KtOAdFbEEnOtv/VZy05pJ2H41xRgUHiGdtMW/vMSeq6XX3IJN8eW2zd0cJTgkFn0ioAlYvID8zRhcvkFHg60QXquoqtp5y65dxjtVz79hefxSo7FO1NhMZBQWE9Tg6R7XkoyTMth62+T9vqOgu2Hms6M=
    if: (branch = main) AND (type = push)
    on_success: change # default: always
jobs:
  include:
    - stage: "Tests"
      name: "Coverage"
      script: ./travis/release.sh    
    - name: "Release Tests"
      script: ./travis/verify.sh
    - stage: "Verify"
      script: npm pack &> /dev/null
