language: node_js
node_js:
  - "16"
addons:
  chrome: stable
  firefox: latest
script:
  - npm --silent run deploy-status -- --status pending --message 'Waiting for build'

  - npm --silent run eslint
  - npm --silent run markdownlint
  - npm --silent run prettier-check

  - npm --silent run build

  - npm --silent run coverage -- --browsers FirefoxHeadless --webgl-stub --failTaskOnError --suppressPassed

  - travis_wait 20 npm --silent run website-release -- --concurrency 1
  - npm pack &> /dev/null

  - npm --silent run build-apps

  - npm --silent run deploy-s3 -- -c 'public, max-age=1800' --confirm
  - npm --silent run deploy-status -- --status success --message Deployed
