language: node_js
node_js:
  - "16"
addons:
  chrome: stable
  firefox: latest
notifications:
  slack:
    secure: JKzk2sJSbZ9h2PUVWj6KtOAdFbEEnOtv/VZy05pJ2H41xRgUHiGdtMW/vMSeq6XX3IJN8eW2zd0cJTgkFn0ioAlYvID8zRhcvkFHg60QXquoqtp5y65dxjtVz79hefxSo7FO1NhMZBQWE9Tg6R7XkoyTMth62+T9vqOgu2Hms6M=
    if: (branch = main) AND (type = push)
    on_success: change # default: always
before_script: pip install awscli --user
jobs:
  include:
    - stage:
      name: "Coverage"
      script:
        - npm --silent run build -- --node
        - npm --silent run coverage -- --browsers FirefoxHeadless --webgl-stub --failTaskOnError --suppressPassed
        - aws s3 sync s3://cesium-dev/cesium/$TRAVIS_BRANCH/Build/Coverage ./Build/Coverage --dryrun --delete --color on
    - name: "Release Tests"
      script: ./travis/test-release.sh
    - name: "Linting, Deployment"
      script:
        - ./travis/prepare.sh
        - npm --silent run deploy-status -- --status pending --message 'Waiting for build'
        - npm --silent run eslint
        - npm --silent run markdownlint
        - npm --silent run prettier-check
        - ./travis/release.sh
        - ./travis/deploy.sh

